import re

def brain(x):
    x = re.sub('MCICPWTDGTEMYGTNRGHTFVSQPCGGHTSTVAHIYFFKVAERDGTIHGTTGCCTHPGPGLWCRRQQVVNFWFIHHDSIYAINCNTQCDYAAGHITRAGTCKTFNSDHGSVNCQTPIEGALAMFTKCRDPFYKSASTKHDEQIFTNNFD', '', x)
    x = re.sub('G', 'G', x)
    x = re.sub('T', 'T', x)
    x = re.sub('C', 'C', x)
    x = re.sub('A', 'A', x)
    return x

brain("Neon DNA (SCITECH_ANALYSIS_BATTERY_CHEMISTRY_1770923224059)")