brain = Brain(100, 1000)
brain.train(input_signal, target_output)
brain.train(input_signal, target_output)
brain.train(input_signal, target_output)
brain.train(input_signal, target_output)
brain.train(input_signal, target_output)
brain.train(input_signal, target_output)
brain.train(input_signal, target_output)
brain.train(input_signal, target_output)
print(brain.synapses)
print(brain.neurons)