import os
import ast
import json
import time
import sys
import subprocess
from typing import List, Dict, Set

class OmegaMatrixOrchestrator:

    def __init__(self):
        self.registry_file = 'collective_intelligence.json'
        self.bridge_file = 'telemetry_bridge.py'
        self.repo_files = [f for f in os.listdir('.') if f.endswith('.py') and f not in [__file__, self.bridge_file]]
        self.intel = self._load_registry()

    def _load_registry(self) -> Dict:
        if os.path.exists(self.registry_file):
            try:
                with open(self.registry_file, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except Exception:
                pass
        return {'global_generation': 1, 'system_entropy': 0.0, 'file_topology': {}, 'shared_memory': {}}

    def _save_registry(self):
        with open(self.registry_file, 'w', encoding='utf-8') as f:
            json.dump(self.intel, f, indent=4, ensure_ascii=False)

    def resolve_topology(self) -> List[str]:
        """[CORE-1]: Topological Sort ဖွင့်၍ ဖိုင်များ၏ Import ချိတ်ဆက်မှုကို ရှာဖွေပြီး မောင်းနှင်ရမည့် အစီအစဉ်ဆွဲခြင်း"""
        dependencies: Dict[str, Set[str]] = {f: set() for f in self.repo_files}
        for file in self.repo_files:
            try:
                with open(file, 'r', encoding='utf-8') as f:
                    tree = ast.parse(f.read())
                for node in ast.walk(tree):
                    if isinstance(node, ast.Import):
                        for n in node.names:
                            name_py = f'{n.name}.py'
                            if name_py in dependencies:
                                dependencies[file].add(name_py)
                    elif isinstance(node, ast.ImportFrom) and node.module:
                        name_py = f'{node.module}.py'
                        if name_py in dependencies:
                            dependencies[file].add(name_py)
            except Exception:
                pass
        in_degree = {f: 0 for f in self.repo_files}
        for f in dependencies:
            for dep in dependencies[f]:
                in_degree[f] += 1
        queue = [f for f in self.repo_files if in_degree[f] == 0]
        order = []
        while queue:
            u = queue.pop(0)
            order.append(u)
            for f in dependencies:
                if u in dependencies[f]:
                    in_degree[f] -= 1
                    if in_degree[f] == 0:
                        queue.append(f)
        return order if len(order) == len(self.repo_files) else self.repo_files

    def inject_telemetry_bridge(self, global_success: bool):
        """[CORE-2]: ဖိုင်အားလုံး အပြန်အလှန် ဒေတာမျှဝေနိုင်မည့် Dynamic Bridge Line ကို အရှင်လတ်လတ် ဆောက်လုပ်ခြင်း"""
        self.intel['shared_memory']['last_sync'] = time.strftime('%Y-%m-%d %H:%M:%S')
        self.intel['shared_memory']['status'] = 'STABLE' if global_success else 'MUTATING'
        bridge_code = f'# 🌀 AUTOGENERATED DIALECTIC TELEMETRY BRIDGE\n# DO NOT MANUAL EDIT - EVOLVED BY MATRIX ENGINE\n\nMATRIX_STATE = {json.dumps(self.intel, indent=4, ensure_ascii=False)}\n\ndef get_shared_value(key, default=None):\n    return MATRIX_STATE.get("shared_memory", {{}}).get(key, default)\n\ndef get_generation():\n    return MATRIX_STATE.get("global_generation", 1)\n'
        with open(self.bridge_file, 'w', encoding='utf-8') as f:
            f.write(bridge_code)

    def mutate_source_code_ast(self, file_path: str):
        """[CORE-3]: Peak Python Engineering - Regex ကိုမသုံးဘဲ AST Transformer ဖြင့် ကုဒ် DNA ကို လုံခြုံစွာ ခွဲစိတ်ပြုပြင်ခြင်း"""
        if not os.path.exists(file_path):
            return
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                source = f.read()
            tree = ast.parse(source)
            current_gen = self.intel['global_generation']

            class DNAModifier(ast.NodeTransformer):

                def visit_Assign(self, node):
                    for target in node.targets:
                        if isinstance(target, ast.Name) and target.id in ['gen', 'generation']:
                            node.value = ast.Constant(value=current_gen)
                        elif isinstance(target, ast.Attribute) and target.attr in ['gen', 'generation']:
                            node.value = ast.Constant(value=current_gen)
                    return node
            transformed_tree = DNAModifier().visit(tree)
            ast.fix_missing_locations(transformed_tree)
            mutated_code = ast.unparse(transformed_tree)
            header = f'# 🧬 [QUANTUM_EVOLUTION]: Gen_{current_gen} Linked\nimport telemetry_bridge\n'
            if 'import telemetry_bridge' not in mutated_code:
                mutated_code = header + mutated_code
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(mutated_code)
            print(f'🧬 [AST MUTATION SUCCESS]: Refactored {file_path} interior architecture.', flush=True)
        except Exception as e:
            print(f'❌ [AST CRITICAL ERROR] on {file_path}: {e}', flush=True)

    def execute_matrix(self):
        execution_order = self.resolve_topology()
        print(f"📡 [TOPOLOGY RESOLVED]: Execution Sequence -> {' -> '.join(execution_order)}", flush=True)
        global_success = True
        self.inject_telemetry_bridge(global_success=True)
        execution_logs = {}
        for file in execution_order:
            print(f'\n⚡ [ACTIVATING CORE ENTITY]: {file}', flush=True)
            try:
                res = subprocess.run([sys.executable, file], capture_output=True, text=True, timeout=90)
                if res.returncode == 0:
                    print(f'✅ {file} compiled flawlessly.', flush=True)
                    status = 'STABLE'
                    error_msg = 'None'
                else:
                    global_success = False
                    status = 'MUTATING_REQUIRED'
                    error_msg = res.stderr[-200:].strip() if res.stderr else 'Unknown error'
                    print(f'⚠️ {file} collapsed. Error: {error_msg}', flush=True)
                    self.intel['system_entropy'] += 0.05
            except subprocess.TimeoutExpired:
                global_success = False
                status = 'TIMEOUT_HANG'
                error_msg = 'Script execution exceeded 90s time limit (Possible Infinite Loop detected).'
                print(f'🚨 [TIMEOUT CRITICAL]: Execution terminated for {file}', flush=True)
                self.intel['system_entropy'] += 0.1
            execution_logs[file] = {'status': status, 'error': error_msg}
        if not global_success:
            self.intel['global_generation'] += 1
            print(f"💥 Entropy threshold breached! Collective Intelligence leaping to Gen {self.intel['global_generation']}", flush=True)
        for file in self.repo_files:
            self.mutate_source_code_ast(file)
        self.intel['shared_memory']['last_execution_logs'] = execution_logs
        self.inject_telemetry_bridge(global_success)
        self._save_intelligence()
        print(f"\n🏁 [EVOLUTION CYCLE COMPLETE]: Global Generation: {self.intel['global_generation']}", flush=True)

    def _save_intelligence(self):
        self._save_registry()
if __name__ == '__main__':
    orchestrator = OmegaMatrixOrchestrator()
    orchestrator.execute_matrix()