import os
import ast
import json
import time
import sys
import subprocess
from typing import List, Dict, Set


class OmegaMatrixOrchestrator:
    def __init__(self):
        self.registry_file = "collective_intelligence.json"
        self.bridge_file = "telemetry_bridge.py"
        self.repo_files = [
            f
            for f in os.listdir(".")
            if f.endswith(".py") and f not in [__file__, self.bridge_file]
        ]
        self.intel = self._load_registry()

    def _load_registry(self) -> Dict:
        if os.path.exists(self.registry_file):
            with open(self.registry_file, "r", encoding="utf-8") as f:
                return json.load(f)
        return {
            "global_generation": 1,
            "system_entropy": 0.0,
            "file_topology": {},
            "shared_memory": {},
        }

    def _save_registry(self):
        with open(self.registry_file, "w", encoding="utf-8") as f:
            json.dump(self.intel, f, indent=4, ensure_ascii=False)

    def resolve_topology(self) -> List[str]:
        """[CORE-1]: Topological Sort ဖွင့ျ ဖိုငျမြား၏ Import ခြိတျဆကျမှုကို ရှာဖှပွေီး မောငျးနှငျရမည့ျ အစီအစဉျဆှဲခွငျး"""
        dependencies: Dict[str, Set[str]] = {f: set() for f in self.repo_files}

        for file in self.repo_files:
            try:
                with open(file, "r", encoding="utf-8") as f:
                    tree = ast.parse(f.read())
                for node in ast.walk(tree):
                    # import X သို့မဟုတျ from X import Y မြားကို လိုကျရှာခွငျး
                    if isinstance(node, ast.Import):
                        for n in node.names:
                            name_py = f"{n.name}.py"
                            if name_py in dependencies:
                                dependencies[file].add(name_py)
                    elif isinstance(node, ast.ImportFrom) and node.module:
                        name_py = f"{node.module}.py"
                        if name_py in dependencies:
                            dependencies[file].add(name_py)
            except Exception:
                pass

        # Topological sorting (Kahn's Algorithm)
        in_degree = {f: 0 for f in self.repo_files}
        for f in dependencies:
            for dep in dependencies[f]:
                in_degree[f] += 1

        queue = [f for f in self.repo_files if in_degree[f] == 0]
        order = []

        while queue:
            u = queue.pop(0)
            order.append(u)
            for f in dependencies:
                if u in dependencies[f]:
                    in_degree[f] -= 1
                    if in_degree[f] == 0:
                        queue.append(f)

        return order if len(order) == len(self.repo_files) else self.repo_files

    def inject_telemetry_bridge(self, global_success: bool):
        """[CORE-2]: ဖိုငျအားလုံး အပွနျအလှနျ ဒတောမြှဝနေိုငျမည့ျ Dynamic Bridge Line ကို အရှငျလတျလတျ ဆောကျလုပျခွငျး"""
        self.intel["shared_memory"]["last_sync"] = time.strftime("%Y-%m-%d %H:%M:%S")
        self.intel["shared_memory"]["status"] = (
            "STABLE" if global_success else "MUTATING"
        )

        bridge_code = f"""# 🌀 AUTOGENERATED DIALECTIC TELEMETRY BRIDGE
# DO NOT MANUAL EDIT - EVOLVED BY MATRIX ENGINE

MATRIX_STATE = {json.dumps(self.intel, indent=4, ensure_ascii=False)}

def get_shared_value(key, default=None):
    return MATRIX_STATE.get("shared_memory", {{}}).get(key, default)

def get_generation():
    return MATRIX_STATE.get("global_generation", 1)
"""
        with open(self.bridge_file, "w", encoding="utf-8") as f:
            f.write(bridge_code)

    def mutate_source_code_ast(self, file_path: str):
        """[CORE-3]: Peak Python Engineering - Regex ကိုမသုံးဘဲ AST Transformer ဖွင့ျ ကုဒျ DNA ကို လုံခွုံစှာ ခှဲစိတျပွုပွငျခွငျး"""
        if not os.path.exists(file_path):
            return

        try:
            with open(file_path, "r", encoding="utf-8") as f:
                source = f.read()

            tree = ast.parse(source)
            current_gen = self.intel["global_generation"]

            # AST Node Transformer ဖွင့ျ ကုဒျထဲက generation / gen တနျဖိုးမြားကို တိုကျရိုကျပွောငျးလဲခွငျး
            class DNAModifier(ast.NodeTransformer):
                def visit_Assign(self, node):
                    for target in node.targets:
                        if isinstance(target, ast.Name) and target.id in [
                            "gen",
                            "generation",
                        ]:
                            node.value = ast.Constant(value=current_gen)
                        elif isinstance(target, ast.Attribute) and target.attr in [
                            "gen",
                            "generation",
                        ]:
                            node.value = ast.Constant(value=current_gen)
                    return node

            transformed_tree = DNAModifier().visit(tree)
            ast.fix_missing_locations(transformed_tree)

            # ပွုပွငျပွီးသား AST ကို ကုဒျအဖွဈ ပွနျပွောငျးပွီး ထိပျဆုံးတှငျ Matrix Header ထည့ျခွငျး
            mutated_code = ast.unparse(transformed_tree)
            header = f"# 🧬 [QUANTUM_EVOLUTION]: Gen_{current_gen} Linked\nimport telemetry_bridge\n"

            if "import telemetry_bridge" not in mutated_code:
                mutated_code = header + mutated_code

            with open(file_path, "w", encoding="utf-8") as f:
                f.write(mutated_code)

            print(
                f"🧬 [AST MUTATION SUCCESS]: Refactored {file_path} interior architecture."
            )
        except Exception as e:
            print(f"❌ [AST CRITICAL ERROR] on {file_path}: {e}")

    def execute_matrix(self):
        execution_order = self.resolve_topology()
        print(
            f"📡 [TOPOLOGY RESOLVED]: Execution Sequence -> {' -> '.join(execution_order)}"
        )

        global_success = True

        # ၁။ ပထမအကွိမျ Bridge ဆောကျပေးခွငျး (ဖိုငျမြား Import လုပျနိုငျရနျ)
        self.inject_telemetry_bridge(global_success=True)

        for file in execution_order:
            print(f"\n⚡ [ACTIVATING CORE ENTITY]: {file}")
            res = subprocess.run([sys.executable, file], capture_output=True, text=True)

            if res.returncode == 0:
                print(f"✅ {file} compiled flawlessly.")
            else:
                global_success = False
                print(f"⚠️ {file} collapsed. Error: {res.stderr[-200:].strip()}")
                self.intel["system_entropy"] += 0.05

        # ၂။ မောငျးနှငျမှုရလဒျပေါျမူတညျပွီး မြိုးဆကျ (Gen) မွှင့ျတငျခွငျး
        if not global_success:
            self.intel["global_generation"] += 1
            print(
                f"💥 Entropy threshold breached! Collective Intelligence leaping to Gen {self.intel['global_generation']}"
            )

        # ၃။ ဖိုငျအားလုံးရဲ့ ကုဒျ DNA ကို AST စနဈဖွင့ျ တိုကျရိုကျ ဝငျရောကျပွငျဆငျခွငျး
        for file in self.repo_files:
            self.mutate_source_code_ast(file)

        # ၄။ နောကျဆုံးအခွအေနဖွေင့ျ Bridge ကို ပွနျလညျရေးသားပွီး သိမျးဆညျးခွငျး
        self.inject_telemetry_bridge(global_success)
        self._save_intelligence()
        print(
            f"\n🏁 [EVOLUTION CYCLE COMPLETE]: Global Generation: {self.intel['global_generation']}"
        )


if __name__ == "__main__":
    orchestrator = OmegaMatrixOrchestrator()
    orchestrator.execute_matrix()
